Dfr 2648 auto redirect to confidential party function not working
hmcts/finrem-ccd-definitions pull request #1702
Opened 2024-03-26 11:22 UTC by hamzahtahirhmcts

### Jira link (if applicable)
[DFR-2648](https://tools.hmcts.net/jira/browse/DFR-2648)

### Change description ###
For both consented and contested cases:

History tab to have TabDisplayOrder = 1
Confidential Applicant tab to have TabDisplayOrder = 2
Confidential Respondent tab to have TabDisplayOrder = 3
All other tabs to have TabDisplayOrder incremented to place them after Confidential Respondent.

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-03-26 11:26 UTC, hamzahtahirhmcts commented
Will create a preview environment once approved :)

2024-03-26 16:57 UTC, jthmcts requested changes
Could you move the Confidential Applicant and Confidential Respondent json to be in order too in the CaseTypeTab.json files

2024-03-27 13:27 UTC, jthmcts approved these changes

2024-07-10 15:06 UTC, jthmcts commented
This PR is obsolete. Replaced by https://github.com/hmcts/finrem-ccd-definitions/pull/1766

2024-07-10 15:06 UTC, closed without merging