Creating new Confidential Document collections for filtered documents
hmcts/finrem-ccd-definitions pull request #365
Opened 2021-01-06 13:16 UTC by HarryH96

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/FR-1884

### Change description ###
- Creating new Confidential Document collection for applicant and respondent documents to be filtered into
- Creating permissions for these confidential fields, only visable to the relevant party

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-01-07 12:37 UTC, shaunganley approved these changes

2021-01-07 13:01 UTC, ravinderpal approved these changes
👍

2021-01-07 13:42 UTC, jakub-kozlowski approved these changes

2021-01-13 15:02 UTC, shaunganley requested changes
I believe you only need to have the auth in non-prod file

2021-01-14 10:31 UTC, shaunganley approved these changes

2021-01-14 11:14 UTC, merged