AC1  Add new Manage case document event in CaseEvent.json and added a…
hmcts/finrem-ccd-definitions pull request #716
Opened 2022-05-16 16:31 UTC by MindGames2015

…n AuthorisationCaseEvent.json object.

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DFR-907

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-06-15 10:55 UTC, gmikerlemos requested changes

2022-06-15 10:55 UTC, gmikerlemos commented on definitions/contested/json/CaseEvent/CaseEvent.json
> +    "CallBackURLAboutToStartEvent": "${CCD_DEF_COS_URL}/case-orchestration/manage-case-documents",
please migrate this to the single callback controller as per dfr1018

2022-06-15 10:55 UTC, gmikerlemos commented on definitions/contested/json/ComplexTypes/ComplexTypes.json
> +    "ListElementCode": "DocumentType",
why is this a Text and not a fixed list? what kind of document types are accepted? is it document file extension instead?

2022-06-22 08:42 UTC, ruban72 approved these changes

2022-06-29 17:29 UTC, MindGames2015 commented
Closing this pr as this is now tracked by this pr #779

2022-06-29 17:30 UTC, closed without merging