DFR-761: Added json object in CaseField.json with ID civilPartnership…
hmcts/finrem-ccd-definitions pull request #807
Opened 2022-07-21 16:12 UTC by MindGames2015

…-newPaperCase and another json object to CaseEventToFields-newPaperCase.json with id civilPartnership-newPaperCase

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

https://tools.hmcts.net/jira/browse/DFR-761

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-07-26 08:01 UTC, EllisD-B submitted a review, later dismissed

2022-08-26 12:24 UTC, rishikrsharma requested changes
This change not needed.

2022-08-26 12:24 UTC, rishikrsharma commented on yarn-audit-known-issues
> +{"type":"auditAdvisory","data":{"resolution":{"id":1081008,"path":"@hmcts/nodejs-healthcheck>@hmcts/nodejs-logging>moment","dev":false,"optional":false,"bundled":false},"advisory":{"findings":[{"vers
not needed

2022-08-30 14:05 UTC, MindGames2015 commented on definitions/contested/json/CaseEventToFields/CaseEventToFields-newPaperCase.json
> +    "CaseFieldID": "civilPartnership",
[This ](https://github.com/hmcts/finrem-case-orchestration-service/pull/770/files#diff-f4167e3b25b9e7c99ba1f1dd6676a16e48c6916955caa92d02a644b21ca38677R121)
Here is the pr Rishi with callback change, that defaults to no. Thanks

2022-08-30 14:10 UTC, MindGames2015 commented on yarn-audit-known-issues
> +{"type":"auditAdvisory","data":{"resolution":{"id":1081008,"path":"@hmcts/nodejs-healthcheck>@hmcts/nodejs-logging>moment","dev":false,"optional":false,"bundled":false},"advisory":{"findings":[{"vers
This was showing as a merge conflict Rishi, so I corrected this. Thanks.

2022-09-02 11:17 UTC, closed without merging