Dfr 1497 add ready for hearing state
hmcts/finrem-ccd-definitions pull request #991
Opened 2023-01-03 13:10 UTC by dawudgovuk

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DFR-1497

### Change description ###
FR Consent: Create new 'Ready For Hearing' state

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-03 15:35 UTC, MindGames2015 approved these changes

2023-01-03 16:29 UTC, rishikrsharma commented on definitions/consented/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
> +    "LiveFrom": "01/12/2022",
no new event needed. These event already exists. As permission set for all

2023-01-03 16:29 UTC, rishikrsharma requested changes
check my comments

2023-01-03 18:02 UTC, rishikrsharma commented on definitions/consented/json/CaseEvent/CaseEvent.json
> +  {
New event is still here.

2023-01-04 13:45 UTC, rishikrsharma commented on definitions/consented/json/CaseEvent/CaseEvent.json
> +    "PreConditionState(s)": "awaitingInfo;readyForHearing",
This seems wrong - as per requirement - this change need on Upload document event

2023-01-12 11:14 UTC, rishikrsharma approved these changes

2023-01-12 15:36 UTC, merged