Dfr 1464 ga status event for old case
hmcts/finrem-ccd-definitions pull request #996
Opened 2023-01-05 12:08 UTC by rishikrsharma

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
Dfr 1464

### Change description ###
ga status event for old case

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-01-10 11:04 UTC, dawudgovuk requested changes

2023-01-10 11:04 UTC, dawudgovuk commented on definitions/contested/json/CaseEvent/CaseEvent.json
> +    "DisplayOrder": 146,
Dupllicated "DisplayOrder": 146 in line 1241

2023-01-19 09:54 UTC, dawudgovuk approved these changes

2023-01-19 09:58 UTC, ruban72 approved these changes

2023-01-19 10:06 UTC, merged